config/routes.rb
Rails.application.routes.draw do


  resources :interventions do
    collection do 
      get :get_buildings_for_customer
      get :get_batteries_for_building
      get :get_columns_for_battery
      get :get_elevators_for_column
    end
  end

  resources :interventions

  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"

  devise_for :employees
  devise_for :users
  
 #get "users/sign_out" => 'pages#index'
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root 'pages#index'

  # get 'userinfo' => 'pages#userinfo'

  delete 'userinfo' => 'pages#destroy'

  delete 'index' => 'pages#destroy'





 post 'index' => 'pages#create'
 
 mount Blazer::Engine, at: "blazer"

  get 'home' => 'pages#home'


  get 'corporate'  => 'pages#corporate'

  get 'residential'  => 'pages#residential'

  get 'submission' => 'quotes#submission'

  post 'submission' => 'quotes#create'
 
  #get 'interventions' => 'interventions#index'

  get 'employee' => 'pages#employee'

  get 'submission' => 'pages#submission'

  
  get 'index' => 'pages#index'

  get 'users/index' => 'pages#index'
  
  get 'users/index' => 'pages#index'
  
  
  get 'employee' => 'pages#employee'
  
  get 'dashboard' => 'pages#dashboard'

  # Dropbox related routings
  # get 'dropbox/auth' => 'dropbox#auth'
  # get 'dropbox/auth_callback' => 'dropbox#auth_callback'

  get 'map' => 'gmap#gmap'
  
  get '/watson/watson' => 'watson#watson'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  
  get 'covid' => 'pages#covid'

  # just for tests RSpec
  # get 'users/interventions' => 'interventions#index'
  get '/font/revicons.woff' => 'pages#home'
  get '/assets/loader.gif' => 'pages#home'
  get '/font/revicons.ttf' => 'pages#home'
end

app/models/intervention.rb
class Intervention < ApplicationRecord
    # belongs_to :employee
   
end

app/controllers/interventions_controller.rb
require 'zendesk_api'
class InterventionsController < ApplicationController
  before_action :set_intervention, only: [:show, :edit, :update, :destroy]

  # GET /interventions
  # GET /interventions.json
  def index
    @interventions = Intervention.all
  end

  # GET /interventions/1
  # GET /interventions/1.json
  def show
  end

  # GET /interventions/new
  def new
    @intervention = Intervention.new(intervention_params)
  end

  # GET /interventions/1/edit
  def edit
  end

  # POST /interventions
  # POST /interventions.json
  def create
    p ("######################### CREATE ######################################")
    puts intervention_params

    @intervention = Intervention.new(intervention_params)
    

    respond_to do |format|
      if @intervention.save
        p ("+++++++++++++++++ Save OK +++++++++++++++++")
        puts ("intervention parameters: ")
        puts  intervention_params
        
        format.html { redirect_to interventions_url }
        # format.html { redirect_to @intervention, notice: 'Intervention was successfully created.' }
        format.json { render :show, status: :created, location: @intervention }
      else
        p ("$$$$$$$$$$$$ not saved - from controller $$$$$$$$$$$$$$$")
        format.html { render :new }
        format.json { render json: @intervention.errors, status: :unprocessable_entity }
      end
    end

  # Zendesk
    # ZendeskAPI::Ticket.create!($client, 
    #  :subject => "Intervention ID#{@intervention.id}",
    #  :comment => { :value => "Details of the intevention:
    #   - Requester ID:#{@intervention.author_id} 
    #   - Customer :#{@intervention.customer_id} 
    #   - Building ID: #{@intervention.building_id} 
    #   - Column ID: #{@intervention.column_id}
    #   - Elevator ID: #{@intervention.elevator_id} 
    #   - Assigned employee ID: #{@intervention.employee_id} 
    #   - Description: #{@intervention.report}"},
    #  :type => "question",
    #  :priority => "normal")
  end

  # PATCH/PUT /interventions/1
  # PATCH/PUT /interventions/1.json
  def update
    respond_to do |format|
      if @intervention.update(intervention_params)
        format.html { redirect_to @intervention, notice: 'Intervention was successfully updated.' }
        format.json { render :show, status: :ok, location: @intervention }
      else
        format.html { render :edit }
        format.json { render json: @intervention.errors, status: :unprocessable_entity }
      end
    end
  end



  # DELETE /interventions/1
  # DELETE /interventions/1.json
  def destroy
    @intervention.destroy
    respond_to do |format|
      format.html { redirect_to interventions_url, notice: 'Intervention was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # ====== Cascade menus ===========
  def get_buildings_for_customer
    puts "get_buildings_for_customer"
    puts params
    @buildings = Building.where("customer_id = ?", params[:customer_id])
    puts "here are the buildings:"
    puts @buildings
    respond_to do |format|
    format.json { render :json => @buildings }
    end
  end
  
  def get_batteries_for_building
    puts "get_batteries_for_building"
    puts params
    @batteries = Battery.where("building_id = ?", params[:building_id])
    puts "here are the batteries:"
    puts @batteries
    respond_to do |format|
    format.json { render :json => @batteries }
    end
  end
  
  def get_columns_for_battery
    puts "get_columns_for_battery"
    puts params
    @columns = Column.where("battery_id = ?", params[:battery_id])
    respond_to do |format|
    format.json { render :json => @columns }
    end
  end

  def get_elevators_for_column
    puts "get_elevators_for_column"
    puts params
    @elevators = Elevator.where("column_id = ?", params[:column_id])
    respond_to do |format|
    format.json { render :json => @elevators }
    end
  end

 
  # ====== /Cascade menus ===========
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_intervention
      @intervention = Intervention.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def intervention_params
      params.fetch(:intervention, {}).permit(:author_id, :customer_id, :building_id, :battery_id, :column_id, :elevator_id, :employeeID, :start_date, :end_date, :result, :report, :status)
    end
end

app/helpers/interventions_helper.rb
module InterventionsHelper
end

app/views/interventions/_form.html.erb
<%= form_with(model: intervention, local: true) do |f| %>
  <% if intervention.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(intervention.errors.count, "error") %> prohibited this intervention from being saved:</h2>

      <ul>
      <% intervention.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
  <div class="row">
    <div class="col-md-5">
    <h1 class="form_title">Intervention Case</h1>
      <%= f.hidden_field :author_id, { :value => current_user.id } %>
      <div class="control-group">
        <%= f.label :customer_id, class:'control-label'%>
        <div class="controls">
          <%= collection_select( :intervention, :customer_id, Customer.order(:business_name), :id, :business_name, {prompt: 'Select Customer'}, { :multiple => false} )%>
        </div>
      </div>
      <br>
      <div class="control-group">
        <%= f.label :building_id, class:'control-label'%>
        <div class="controls">
          <%= grouped_collection_select( :intervention, :building_id, Customer.order(:business_name), :buildings, :business_name, :id, :id, {prompt: 'Select Building'}, { :multiple => false} )%>
        </div>
      </div>   
      <br> 
      <div class="control-group">
        <%= f.label :battery_id, class:'control-label' %>
        <div class="controls">
          <%= collection_select( :intervention, :battery_id, Battery.all, :id, :id,{prompt: 'Select Battry'}, { :multiple => false} ) %>
        </div>
      </div> 
      <br>
      <div class="control-group">
        <%= f.label :column_id, class:'control-label'%>
        <div class="controls">
          <%= collection_select( :intervention, :column_id, Column.all, :id, :id, {prompt: 'None'}, { :multiple => false} )%>
        </div>
      </div> 
      <br>
      <div class="control-group">
        <%= f.label :elevator_id, class:'control-label'%>
        <div class="controls">
          <%= collection_select( :intervention, :elevator_id, Elevator.all, :id, :id, {prompt: 'None'}, { :multiple => false} )%>
        </div>
      </div> 
      <br>  
    </div>

    <div class="col-md-2">
    </div>

    <div class="col-md-5">
      <h1 class="form_title" id="form_title_1">Details</h1>
      <div class="control-group">
        <%= f.label :employee_id, class:'control-label'%>
        <div class="controls">
          <%= collection_select( :intervention, :employee_id, Employee.all, :id, :firstName, {prompt: 'Assigne Employee'}, { :multiple => false} )%>
        </div>
      </div> 
      <br>  
      <div class="control-group">
        <%= f.label :report, 'Description', class:'control-label'%>
        <div class="controls">
          <%= f.text_area(:report, {:class => 'form-control'})%>
        </div>
      </div> 
    </div>
  </div>



  <%= f.submit class: 'btn btn-warning'%>
  </div>
<% end %>

<%# ==================== SCRIPT ==================== %>
<script>
  // A $( document ).ready() block.
  $( document ).ready(function() {
    console.log( "ready!" );

    cust = $("#intervention_customer_id");
    build = $('#intervention_building_id');
    batt = $('#intervention_battery_id');
    col = $('#intervention_column_id');
    elev = $('#intervention_elevator_id');

   
    // build.css("visibility", "hidden");
    
    
    build.css("visibility", "hidden");
    batt.css("visibility", "hidden");
    col.css("visibility", "hidden");
    elev.css("visibility", "hidden");
// Buildings dropdown menu
    $("#intervention_customer_id").change(function() {
      
      if(cust == ''){
         
      }else{
        
        build.css("visibility", "visible");
        batt.css("visibility", "hidden");
        col.css("visibility", "hidden");
        elev.css("visibility", "hidden");
      }
      var selected_customer_id = $(this).val();
      console.log( $(this).val() );

      // Serge Savoi notes
      var selected_customer_id = $(this).val();
      $.get('/interventions/get_buildings_for_customer', {customer_id: selected_customer_id}, function(result) {

        var buildings = result["buildings"];
        $("#intervention_building_id").empty();
        $("#intervention_building_id").append('<option>Select Building</option>');
        $.each(result, function(i, j) {
          var row = '<option value="' + j.id + '">' + j.id + '</option>';
          // console.log(row);
          $(row).appendTo("#intervention_building_id")
        });
      });
    });

  // Batteries dropdown menu
  $("#intervention_building_id").change(function() {
      if(build == ''){
        // document.getElementById("intervention_battery_id").style.visibility = "hidden";
        
      }else{
        batt.css("visibility", "visible");
        col.css("visibility", "hidden");
        elev.css("visibility", "hidden");
      }
      var selected_building_id = $(this).val();
      console.log('selected building id: ')
      console.log( $(this).val() );
      $.get('/interventions/get_batteries_for_building', {building_id: selected_building_id}, function(result) {

        $("#intervention_battery_id").empty();
        $("#intervention_battery_id").append('<option>Select Battery</option>');
        $.each(result, function(i, j) {
          var row = '<option value="' + j.id + '">' + j.id + '</option>';
          // console.log(row);
          $(row).appendTo("#intervention_battery_id")
        });
      });
    });

  // Column dropdown menu
  $("#intervention_battery_id").change(function() {
      if(batt == ''){
        // document.getElementById("intervention_column_id").style.visibility = "hidden";
      }else{
       col.css("visibility", "visible");
       elev.css("visibility", "hidden");
      }
      var selected_battery_id = $(this).val();
      console.log('selected building id: ')
      console.log( $(this).val() );
      $.get('/interventions/get_columns_for_battery', {battery_id: selected_battery_id}, function(result) {

        $("#intervention_column_id").empty();
        $("#intervention_column_id").append('<option>None</option>');
        $.each(result, function(i, j) {
          var row = '<option value="' + j.id + '">' + j.id + '</option>';
          // console.log(row);
          $(row).appendTo("#intervention_column_id")
        });
      });
    });

  // Elevator dropdown menu
  $("#intervention_column_id").change(function() {
      if(col == ''){
        // document.getElementById("intervention_elevator_id").style.visibility = "hidden";
      }else{
        elev.css("visibility", "visible");
      }
      var selected_column_id = $(this).val();
      console.log('selected building id: ')
      console.log( $(this).val() );
      $.get('/interventions/get_elevators_for_column', {column_id: selected_column_id}, function(result) {

        $("#intervention_elevator_id").empty();
        $("#intervention_elevator_id").append('<option>None</option>');
        $.each(result, function(i, j) {
          var row = '<option value="' + j.id + '">' + j.id + '</option>';
          // console.log(row);
          $(row).appendTo("#intervention_elevator_id")
        });
      });
    });
    
  });

</script>
<%# ==================== /SCRIPT ==================== %>



    

app/views/interventions/edit.html.erb
<h1>Editing Intervention</h1>

<%= render 'form', intervention: @intervention %>

<%= link_to 'Show', @intervention %> |
<%= link_to 'Back', interventions_path %>

app/views/interventions/index.html.erb
<head>
<style>
  .table_interventions{font-size:15px}
</style>
</head>

<body>

<%# ----- To give the access to the employees - part 1/2 ----------- %>
<% if user_signed_in? && current_user.is_employee(current_user.email)  %>


<p id="notice"><%= notice %></p>
<br>
<br>

<div class="container">
<h1>Interventions</h1>
<%= link_to 'New Intervention', new_intervention_path, class: 'btn btn-success btn-md', name: 'New Intervention', id: 'intervnetion', value: 'intervention' %>

<table class="table_interventions">
  <thead>
    <tr>
      
      <th>Author ID</th>
      <th>Customer ID</th>
      <th>Building ID</th>
      <th>Employee ID</th>
      <th>Status</th>
      <th>Result</th>
      <th></th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @interventions.each do |intervention| %>
      <tr>
        <td><%= intervention.author_id %></td>
        <td><%= intervention.customer_id %></td>
        <td><%= intervention.building_id %></td>
        <td><%= intervention.employee_id %></td>
        <td><%= intervention.status %></td>
        <td><%= intervention.result %></td>
        
        
        <td><%= link_to 'Show', intervention, class: 'btn btn-success btn-sm'  %></td>
        <td><%= link_to 'Edit', edit_intervention_path(intervention), class: 'btn btn-success btn-sm'  %></td>
        <%# <td><%= link_to 'Destroy', intervention, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-success btn-sm'  %>
        <%# </td> %>
      </tr>
    <% end %>
  </tbody>
</table>

</div>

<%# ----- To give the access to the employees - part 2/2 ----------- %>
<% else %>
<br><br><br> 
<br><br><br>
    <div class = "container">
        <h1>This page is reserved to the Employees</h1>
        <h4>Please Login with your employee code</h4>
        <%= link_to "Login", new_user_session_path, :class => 'btn btn-warning'  %><br>														
    </div>
<% end %>
</body>

app/views/interventions/new.html.erb
<%# ----- To give the access to the employees - part 1/2 ----------- %>
<% if user_signed_in? && current_user.is_employee(current_user.email)  %>


<div class="container">
<br><br><br> 
    <h1>New Intervention</h1>
    <%= render 'form', intervention: @intervention %>
    <%= link_to 'Back', interventions_path, class: 'btn btn-success btn-sm'%>
</div>
<%# ----- To give the access to the employees - part 2/2 ----------- %>
<% else %>
<br><br><br> 
<br><br><br>
    <div class = "container">
        <h1>This page is reserved to the Employees</h1>
        <h4>Please Login with your employee code</h4>
        <%= link_to "Login", new_user_session_path, :class => 'btn btn-warning'  %><br>														
    </div>
<% end %>

app/views/interventions/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
    <br>
    <h3> New intervention</h3> 
    <div class="row">
    <div class="col-md-4">
        <p>Author ID: <%= @intervention.author_id %></p>
        <p>Intervention ID: <%= @intervention.id %></p>
        <p> Customer ID: <%= @intervention.customer_id%></p>
        <p>Building ID: <%= @intervention.building_id%></p>
    </div>
    <div class="col-md-4">
        <p>Employee ID: <%= @intervention.employee_id%></p>
        <p>Report: <%= @intervention.report%></p>
    </div>
    </div>
    <%= link_to 'Edit', edit_intervention_path(@intervention), class: 'btn btn-success btn-sm'%> |
    <%= link_to 'Back', interventions_path, class: 'btn btn-success btn-sm' %>

</div>